language: php
sudo: required
dist: trusty
php:
  - '5.6'
install:
  - composer install
  - npm install
  - bower install
before_script:
  - mysql -u root
  - CREATE USER $DATABASE_TEST_USER@$DATABASE_TEST_HOST IDENTIFIED BY password($DATABASE_TEST_PASS);
  - GRANT ALL PRIVILEGES ON *.* TO $DATABASE_TEST_USER@$DATABASE_TEST_HOST;
  - FLUSH PRIVILEGES;
  - exit
  - mysql -u $DATABASE_TEST_USER -p$DATABASE_TEST_PASS < protected/modules/sample/sql/openeyes_sample_data.sql
script:
  - mkdir assets
  - mkdir cache
  - cd protected
  - mkdir cache
  - mkdir cache/events
  - mkdir runtime
  - cp config/local.sample/common.php config/local/common.php
  - cp config/local.sample/console.vagrant.php config/local/console.php
  - cp config/local.sample/test.php config/local/test.php
  - php yiic migrate --interactive=0 --connectionID=testdb
  - php yiic migratemodules --interactive=0 --connectionID=testdb
  - php yiic generateuniquecode --interactive=0 --connectionID=testdb
  - php yiic generatesessions --interactive=0 --connectionID=testdb
  - cd protected/tests
  - phpunit ../modules/OECaseSearch/tests/unit
  - phpunit ../modules/OETrial/tests/unit
